### ISSUE TITLE
Report cannot be generated due to missing reference

### ISSUE THREAD

**Issue by syvasoft** [mckayERP/template#4]
When I click Report toolbar button for Business Partner window, I have encountered following exception:

java.lang.NullPointerException
    at com.lowagie.text.pdf.PdfGraphics2D.drawImage(Unknown Source)
    at com.lowagie.text.pdf.PdfGraphics2D.drawImage(Unknown Source)
    at org.compiere.print.layout.TableElement.printColumn(TableElement.java:1458)
    at org.compiere.print.layout.TableElement.paint(TableElement.java:1203)
    at org.compiere.print.layout.Page.paint(Page.java:183)
    at org.compiere.print.layout.LayoutEngine.print(LayoutEngine.java:1867)
    at org.adempiere.pdf.Document.writePDF(Document.java:84)
    at org.adempiere.pdf.Document.getPDFAsFile(Document.java:99)
    at org.compiere.print.ReportEngine.createPDF(ReportEngine.java:948)
    at org.adempiere.webui.window.ZkReportViewer.renderReport(ZkReportViewer.java:343)
    at org.adempiere.webui.window.ZkReportViewer.init(ZkReportViewer.java:276)
    at org.adempiere.webui.window.ZkReportViewer.<init>(ZkReportViewer.java:162)
    at org.adempiere.webui.window.ZkReportViewerProvider.openViewer(ZkReportViewerProvider.java:57)
    at org.compiere.print.ReportCtl.preview(ReportCtl.java:410)
    at org.adempiere.webui.apps.WReport.launchReport(WReport.java:252)
    at org.adempiere.webui.apps.WReport.launchReport(WReport.java:216)
    at org.adempiere.webui.apps.WReport.getPrintFormats(WReport.java:168)
    at org.adempiere.webui.apps.WReport.<init>(WReport.java:87)
    at org.adempiere.webui.panel.AbstractADWindowPanel.onReport(AbstractADWindowPanel.java:1883)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:381)
    at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:345)
    at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
    at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
    at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
    at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

**Comment by syvasoft** [comment]
Hi Mike,
I could not find the source jar for com.lowagie.text.pdf.PdfGraphics2D.drawImage. Do you have any idea about this?
